{% set name = "extra-data" %}
{% set version = "1.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/EXtra-data-{{ version }}.tar.gz
  sha256: fb84a0e8163ca399e061a065b8266302298818ffe6621327fbcaffa435790f92

build:
  entry_points:
    - lsxfel = extra_data.lsxfel:main
    - karabo-bridge-serve-files = extra_data.cli.serve_files:main
    - extra-data-validate = extra_data.validation:main
    - extra-data-make-virtual-cxi = extra_data.cli.make_virtual_cxi:main
    - extra-data-locality = extra_data.locality:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - __unix
  run:
    - python >=3.6
    - h5py >=2.10
    - numpy
    - pandas
    - xarray

test:
  imports:
    - extra_data
  commands:
    - pip check
    - lsxfel --help
    - karabo-bridge-serve-files --help
    - extra-data-validate --help
    - extra-data-make-virtual-cxi --help
    - extra-data-locality --help
  requires:
    - pip

about:
  home: https://github.com/European-XFEL/EXtra-data
  summary: Tools to read and analyse data from European XFEL
  dev_url: https://github.com/European-XFEL/EXtra-data
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RobertRosca
    - takluyver
    - tmichela
