{% set name = "cfelpyutils" %}
{% set version = "2.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cfelpyutils-{{ version }}.tar.gz
  sha256: 218c3742388dec2cf781042dab4f4740c1132eb33d315b8360b848c1580e5231

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools >=42.0
    - wheel
    - cython
    - numpy
    - pip
  run:
    - python
    - h5py >=2.9.0
    - mypy_extensions >=0.4.3
    - pandas >=1.1.5
    - typing >=3.6.4  # [py<37]
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - cfelpyutils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.desy.de/cfel-sc-public/cfelpyutils
  summary: Utility functions and classes for CFEL software projects
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RobertRosca
    - pmiddend
