{% set name = "extra-geom" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/EXtra-geom-{{ version }}.tar.gz
  sha256: d9ca9211a157f87301f3e6fef57ed260d1d8270eeeb198a4b3786639e4d66d81

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - cfelpyutils >=2.0,<3.0
    - h5py >=2.7.1
    - matplotlib-base
    - numpy

test:
  imports:
    - extra_geom
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/European-XFEL/EXtra-geom
  summary: Tools to work with EuXFEL detector geometry and assemble detector images
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - RobertRosca
    - takluyver
    - tmichela
